# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Itervox < Formula
  desc "Autonomous AI agent daemon that drives Linear issues through Claude-powered agentic loops."
  homepage "https://github.com/vnovick/itervox"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vnovick/itervox/releases/download/v0.1.2/itervox_darwin_amd64.tar.gz"
      sha256 "927e395c5f0002acfcddedb2ca99423592ebca3abf1d19190231773ef61ec912"

      define_method(:install) do
        bin.install "itervox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vnovick/itervox/releases/download/v0.1.2/itervox_darwin_arm64.tar.gz"
      sha256 "b2dfd1f3f3c2e41bee85738c9c274110ecdd112fec1e9e281d458040d657659d"

      define_method(:install) do
        bin.install "itervox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vnovick/itervox/releases/download/v0.1.2/itervox_linux_amd64.tar.gz"
      sha256 "055c441f507611adb6d83cd47e08f6b5f86444d0c7b89ac9b96e90e267b507b1"
      define_method(:install) do
        bin.install "itervox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vnovick/itervox/releases/download/v0.1.2/itervox_linux_arm64.tar.gz"
      sha256 "a7f4ad41df52128ab62dd2b6128163d977963ca442df6e7aa06b09840130e641"
      define_method(:install) do
        bin.install "itervox"
      end
    end
  end

  test do
    system "#{bin}/itervox", "--version"
  end
end
