# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Itervox < Formula
  desc "Autonomous AI agent daemon that drives Linear issues through Claude/Codex-powered agentic loops."
  homepage "https://github.com/vnovick/itervox"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vnovick/itervox/releases/download/v0.2.1/itervox_darwin_amd64.tar.gz"
      sha256 "8eb98d776f6a5402edebcbafc50feddb5ab30c24caf39ab52006831cafee2f21"

      define_method(:install) do
        bin.install "itervox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vnovick/itervox/releases/download/v0.2.1/itervox_darwin_arm64.tar.gz"
      sha256 "9353a40d7286ecbabe71a79825b3d62f742cbe10b0d6e5234c58e22e017e723a"

      define_method(:install) do
        bin.install "itervox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vnovick/itervox/releases/download/v0.2.1/itervox_linux_amd64.tar.gz"
      sha256 "1e54899110d09d774f53c9fdacfd027a57564414ecc2c2e1f4a91aa440355118"
      define_method(:install) do
        bin.install "itervox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vnovick/itervox/releases/download/v0.2.1/itervox_linux_arm64.tar.gz"
      sha256 "99473bfd1b3d13b33c97e0810c2a2a99e8ed8c8241f7e26558f0d7fd57aa32f5"
      define_method(:install) do
        bin.install "itervox"
      end
    end
  end

  test do
    system "#{bin}/itervox", "--version"
  end
end
