# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SymphonyGo < Formula
  desc "Autonomous AI agent daemon that drives Linear issues through Claude-powered agentic loops."
  homepage "https://github.com/vnovick/symphony-go"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vnovick/symphony-go/releases/download/v0.0.1/symphony-go_darwin_amd64.tar.gz"
      sha256 "25ac301af24f9aea3785fa49bb61bc133fea4b10778078499a50d51b80852039"

      define_method(:install) do
        bin.install "symphony"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vnovick/symphony-go/releases/download/v0.0.1/symphony-go_darwin_arm64.tar.gz"
      sha256 "5755bf293b83d8257e0c1c9c2305359c2b13b1d713c517d8d9f8e236bca596d4"

      define_method(:install) do
        bin.install "symphony"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vnovick/symphony-go/releases/download/v0.0.1/symphony-go_linux_amd64.tar.gz"
      sha256 "83034458d3d503f9fd01d03cd11cd88bc407ba0be9df9b2d1b8a6babeef2fe60"
      define_method(:install) do
        bin.install "symphony"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vnovick/symphony-go/releases/download/v0.0.1/symphony-go_linux_arm64.tar.gz"
      sha256 "a10d99e84dab8de8b65a80a3bd93845439f165bcaa3e6893573bdc85cadac173"
      define_method(:install) do
        bin.install "symphony"
      end
    end
  end

  test do
    system "#{bin}/symphony", "--version"
  end
end
